packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@babel/generator': ^7.27.1
  '@babel/parser': ^7.27.2
  '@babel/traverse': ^7.27.1
  '@babel/types': ^7.27.1
  '@types/fs-extra': ^11.0.4
  '@types/lodash': ^4.17.16
  add: ^2.0.6
  axios: ^1.9.0
  cheerio: ^1.0.0
  colorette: ^2.0.20
  commander: ^13.1.0
  dotenv: ^16.5.0
  fs-extra: ^11.3.0
  json5: ^2.2.3
  lodash: ^4.17.21
  p-queue: ^8.1.0
  tiny-glob: ^0.2.9
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
